#!/bin/bash

# Step 1: Create the '4_BAND_calculation' folder if it doesn't exist
mkdir -p 4_BAND_calculation

# Step 2: Copy necessary files from '2_SCF' to '4_BAND_calculation'
cp 2_SCF/CONTCAR 2_SCF/INCAR 2_SCF/KPOINTS 2_SCF/POTCAR 2_SCF/WAVECAR 2_SCF/CHGCAR 2_SCF/job.sh 4_BAND_calculation/

# Step 3: Rename 'CONTCAR' to 'POSCAR' in the '4_BAND_calculation' folder
mv 4_BAND_calculation/CONTCAR 4_BAND_calculation/POSCAR

# Step 4: Run VASPkit to generate KPOINTS for band structure calculation
cd 4_BAND_calculation

# Run VASPkit
vaspkit << EOF
302
EOF

# Sleep for 2 seconds to ensure VASPkit has time to generate the KPATH.in file
sleep 2

# Step 4d: Check if 'KPATH.in' file exists, if yes then rename it to 'KPOINTS'
if [ -f KPATH.in ]; then
    cp KPATH.in KPOINTS
else
    echo "Error: KPATH.in file was not generated by VASPkit."
    exit 1
fi
cd ..


# Step 5: Modify the 'INCAR' file LWAVE, LCHARG, ISTART, ICHARG, NEDOS, EMAX, EMIN
# Comment out LWAVE and LCHARG
sed -i 's/^\(\s*LWAVE\s*=\s*.*\)$/# \1/' 4_BAND_calculation/INCAR
sed -i 's/^\(\s*LCHARG\s*=\s*.*\)$/# \1/' 4_BAND_calculation/INCAR
sed -i 's/^\(\s*ISMEAR\s*=\s*.*\)$/# \1/' 4_BAND_calculation/INCAR
sed -i 's/^\(\s*ISTART\s*=\s*\).*/\1 1/' 4_BAND_calculation/INCAR
sed -i 's/^#\s*\(  ICHARG\s*=\s*11\)/\1/' 4_BAND_calculation/INCAR
sed -i '/^\s*ICHARG\s*=\s*11\s*$/a \ \ ADDGRID  = .TRUE.' 4_BAND_calculation/INCAR


# Step 6: Modify the 'job.sh' file
# Change the #PBS -N tag to 4_BAND_calculation
sed -i 's/^#PBS -N .*/#PBS -N 4_BAND_calculation/' 4_BAND_calculation/job.sh

echo "The 4_BAND_calculation folder is created successfully."

# step 7: Ask the user if they want to submit the VASP run
read -p "Do you want to submit the job? (Y/N): " user_input

if [[ "$user_input" == "Y" || "$user_input" == "y" ]]; then
    # If the user inputs Y, submit the job
    cd 4_BAND_calculation
    qsub job.sh
    cd ..
    qstat
elif [[ "$user_input" == "N" || "$user_input" == "n" ]]; then
    # If the user inputs N, exit the script
    echo "Exiting the script."
    exit 0
else
    # If the user inputs anything else, show an error message
    echo "Invalid input. Please enter Y for Yes or N for No."
    exit 1
fi
















